author: sotanishy
description: sotanishy's code snippets for competitive programming
header_pages:
- null
plugins:
- jekyll-remote-theme
remote_theme: jekyll/minima
theme: jekyll-theme-minimal
title: sotanishy's competitive programming library
