author: sotanishy
description: sotanishy's code snippets for competitive programming
plugins:
- jemoji
- jekyll-redirect-from
theme: jekyll-theme-minimal
title: sotanishy's competitive programming library
